// Patterns to always ignore (in addition to .gitignore)
export const BASE_IGNORE_PATTERNS = [
  '.git',
  '.svn',
  '.hg',
  'node_modules',
  '__pycache__',
  '.pytest_cache',
  '.mypy_cache',
  'venv',
  '.venv',
  'env',
  '.env.local',
  '.env.*.local',
  'dist',
  'build',
  'out',
  'target',
  'coverage',
  '.coverage',
  '.nyc_output',
  '.next',
  '.nuxt',
  '.vscode',
  '.idea',
  '*.log',
  '*.lock',
  'pnpm-lock.yaml',
  'package-lock.json',
  'yarn.lock',
  'Cargo.lock',
  'Gemfile.lock',
  'poetry.lock',
  '.DS_Store',
  'Thumbs.db',
  '*.pyc',
  '*.pyo',
  '*.class',
  '*.o',
  '*.so',
  '*.dylib',
  '*.dll',
  '*.exe',
]

// Non-code file extensions that can be excluded via CLI flags
export const EXCLUDABLE_EXTENSIONS = {
  json: ['.json', '.jsonc', '.json5', '.geojson'],
  markdown: ['.md', '.mdx', '.markdown', '.mdown', '.mkd'],
  yaml: ['.yml', '.yaml'],
}
